---
title: "Article 1 : A reliable clock for your microbiome "
author:
  - name: Gambarotto Mélia
date: 10-16-2019
categories:
  - elephant
  - track
preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


This article is from EurekAlert.The [link]( https://www.eurekalert.org/pub_releases/2019-10/wifb-arc101019.php) of the article.




## Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| Samples            | A littel part of something          |
| (to) occur         |   (To)Happen, (to) do,(to) arrive|
|(to) provide         |  (to) bring |
| Set                 |Ensemble/ collection |
| (to) link           |(to) attach |
| Feedback loop       |Loop of return effect  |
| Repressor          |  A things stop transcription of dna |
| Regardless         |  indifferent |
| (to) allow          | (to) authorize  |
| Both                | The two  |
| Rate               |A standar quantity of something   |
| Behavior  |  Conduct|
|  Workflow | A lot of work |
| Outwards  | outside |
|  Pattern |Model/ exemple  |
| Able  |  Can do something / capable |
| Several |   Divers/ a lot |
| Compound  | composit  | 
| (to) load   | (to) charge  |
| Imbalance  | disproportion  |
| Probe |  examination |
| Disturbance  |  perturbation|
| (to) elapse  | The time is over  |
| Within  |  Inti/ inside |



## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | David T. Riglar, David L. Richmond, Laurent Potvin-Trottier, Andrew A. Verdegaal, Alexander D. Naydich, Somenath Bakshi, Emanuele Leoncini, Lorena G. Lyon, Johan Paulsson. They are almost all researchers at Harvard Medical School in Department of Systems Biology. But the article is a summary of the original article. We don’t know who wrote the summary.|
| Published in?                |      11 october 2019                                                 |
| General topic?               |          This article about changes in microbiome patterns analyzes where and when the bacteria in the living gut change and divide themselves. The researchers found a new technique to understand that process.             |
| Procedure/what was examined? | To proceed, they used an oscillating gene circuit (repressilator) to measure the bacterial growth. It consists of three bacterial gene which code for three proteins. They are put into a plasmid in the cytoplasm of mammal. The number of negative feedback loop cycles informs about how many cell divisions are done.
After that, all proteins are colored to verify which protein is activated at a specific time of growth. Finally, the researchers will detect differences in bacterial growth rates in a gut inflammation. They noted that there is wider range of phases in contaminated bacteria growth compared to normal bacteria, resulting in a modified microbiome. |
| Conclusions/discovery?       |    Through this study, we can have a better understanding of the microbiome’s dynamics, allowing an improvement in human gut’s therapeutics.   |
| Remaining questions?         | / |






